# -*- coding: utf-8 -*-
"""
Biblioteka treści sekcji Inspiracje (Cyklia).
Każdy artykuł ma pełną, edukacyjną treść w strukturze:
  content.sections  – lista sekcji: {"h": tytuł, "p": [akapity] | "ul": [punkty]}
  content.info      – box "Warto wiedzieć" {"title", "p"|"items"}
  content.remember  – lista punktów do boxa "Zapamiętaj"
  content.doctor    – lista punktów do boxa "Kiedy skontaktować się z lekarzem?"
  content.summary   – krótkie podsumowanie

phase: period | pre_period | ovulation | follicular | luteal | any
Treści są edukacyjne i nie zastępują porady lekarskiej.
"""

ARTICLES = [
    # ============================================================
    # ZDROWIE REPRODUKCYJNE
    # ============================================================
    {
        "slug": "wczesne-objawy-ciazy",
        "title": "Wczesne objawy ciąży",
        "category": "Zdrowie reprodukcyjne",
        "summary": "Brak miesiączki, tkliwość piersi, zmęczenie, nudności — kiedy mogą pojawić się pierwsze objawy ciąży i co z nimi zrobić.",
        "intro": "Pierwsze objawy ciąży bywają mylące, bo część z nich przypomina zwykły PMS. Warto znać typowe sygnały i wiedzieć, jak je potwierdzić bez domysłów.",
        "read_minutes": 6,
        "illustration": "pregnancy",
        "tone": "lilac",
        "badge": "Popularne",
        "phase": "any",
        "keywords": "ciąża, objawy, brak miesiączki, nudności, test, piersi, zmęczenie",
        "related": ["kiedy-test-ciazowy", "plamienie-czy-okres", "pms"],
        "content": {
            "sections": [
                {"h": "Kiedy mogą pojawić się pierwsze objawy?",
                 "p": ["Najwcześniejsze sygnały zwykle zaczynają się między 1. a 2. tygodniem po zapłodnieniu, czyli mniej więcej w okolicy spodziewanej miesiączki. U części kobiet pojawiają się dopiero po kilku tygodniach, a u części prawie wcale — brak objawów nie wyklucza ciąży."]},
                {"h": "Najczęstsze wczesne objawy ciąży",
                 "ul": ["Brak miesiączki — najbardziej klasyczny sygnał, choć nie zawsze występuje",
                        "Tkliwość i napięcie piersi, wrażliwe sutki",
                        "Wzmożone zmęczenie i senność",
                        "Nudności, czasem z wymiotami (zwłaszcza rano)",
                        "Częstsze oddawanie moczu",
                        "Delikatne plamienie implantacyjne (kilka dni przed terminem miesiączki)",
                        "Zmiany apetytu, wrażliwość na zapachy, lekki zawrót głowy"]},
                {"h": "Brak miesiączki",
                 "p": ["Spóźniająca się miesiączka to najsilniejszy sygnał, ale nie jedyny powód opóźnienia. Stres, zmiana trybu życia, intensywny wysiłek czy zaburzenia hormonalne również przesuwają termin. Jeśli regularnie używasz Cyklii, aplikacja podpowie, o ile dni przekroczony jest przewidywany termin."]},
                {"h": "Tkliwość piersi",
                 "p": ["Ból i wrażliwość piersi to efekt wzrostu progesteronu i estrogenu. To jeden z najbardziej wcześnie pojawiających się objawów — u wielu kobiet odczuwalny jeszcze przed terminem miesiączki."]},
                {"h": "Zmęczenie i nudności",
                 "p": ["Gwałtowny wzrost progesteronu potrafi powodować duże zmęczenie. Nudności najczęściej zaczynają się około 6. tygodnia ciąży i zwykle łagodnieją po pierwszym trymestrze. Jeśli utrudniają jedzenie i picie, zgłoś się do lekarza."]},
                {"h": "PMS a ciąża — podobieństwa",
                 "p": ["Wzdęcia, wrażliwość piersi, zmęczenie i wahania nastroju występują w obu sytuacjach. Różnica jest taka, że przy ciąży objawy nie kończą się wraz z nadejściem miesiączki, a w PMS zwykle ustępują w ciągu kilku dni po jej rozpoczęciu."]},
                {"h": "Kiedy najlepiej zrobić test ciążowy?",
                 "p": ["Test najlepiej wykonać w dniu spodziewanej miesiączki lub później. Wcześniejsze testy mogą dać wynik fałszywie ujemny. Dokładniejsze zasady znajdziesz w artykule o testach ciążowych."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Objawy ciąży nie są diagnostyczne — wiele z nich przypomina PMS",
                               "Jedynym domowym potwierdzeniem jest test ciążowy (a najlepiej powtórzony)",
                               "Napięcie i oczekiwanie same potrafią opóźnić miesiączkę"]},
            "remember": ["Brak miesiączki + tkliwość piersi + zmęczenie to najczęstszy zestaw wczesnych objawów",
                         "Test ciążowy zrób w dniu spodziewanej miesiączki lub później",
                         "Gdy objawy niepokoją lub trwają długo — skonsultuj się z lekarzem"],
            "doctor": ["Silne, nieustające nudności uniemożliwiające jedzenie i picie",
                       "Ból brzucha z towarzyszącym krwawieniem lub zawrotami głowy",
                       "Jednostronny ból podbrzusza (w ciąży może sugerować ciążę pozamaciczną)"],
            "summary": "Wczesne objawy ciąży przypominają PMS, dlatego nie warto oceniać stanu po samopoczuciu. Spokojnie: odczekaj do terminu miesiączki i wykonaj test. Jeśli wynik jest pozytywny albo objawy Cię niepokoją, umów wizytę u ginekologa."
        },
    },
    {
        "slug": "kolor-wydzieliny",
        "title": "Co oznacza kolor wydzieliny z pochwy?",
        "category": "Zdrowie reprodukcyjne",
        "summary": "Przezroczysta, biała, żółta, zielona, różowa, brązowa — co oznacza kolor upławów i kiedy warto skonsultować się z lekarzem.",
        "intro": "Wydzielina z pochwy zmienia się w trakcie cyklu — to normalne i zdrowe. Warto jednak rozróżnić fizjologiczne zmiany od sygnałów, które sugerują infekcję.",
        "read_minutes": 7,
        "illustration": "discharge",
        "tone": "pink",
        "badge": "Popularne",
        "phase": "any",
        "keywords": "wydzielina, upławy, kolor, śluz, infekcja, swędzenie, zapach",
        "related": ["wydzielina-w-fazach", "higiena-intymna", "plamienie-czy-okres"],
        "content": {
            "sections": [
                {"h": "Zdrowa wydzielina i zmiany w trakcie cyklu",
                 "p": ["Fizjologiczna wydzielina jest przejrzysta lub biała, może mieć lekki, niewyczuwalny lub mleczny zapach. Jej konsystencja zmienia się pod wpływem estrogenu: po okresie jest skąpa, przed owulacją śliska i rozciągliwa (jak białko jajka), po owulacji gęstsza i kremowa."]},
                {"h": "Wydzielina przezroczysta i biała",
                 "p": ["Przezroczysta, wodnista lub rozciągliwa wydzielina to oznaka wysokiego poziomu estrogenu i typowy widok w okolicy owulacji. Biała, kremowa wydzielina bez zapachu również jest normalna, szczególnie w drugiej połowie cyklu."]},
                {"h": "Wydzielina żółta i zielona",
                 "p": ["Lekko żółtawy odcień może wynikać po prostu z kontaktu z moczem lub noszenia ciemniejszej bielizny. Jednak wyraźnie żółta lub zielona wydzielina, zwłaszcza o nieprzyjemnym zapachu, z towarzyszącym świądem lub pieczeniem, może wskazywać na infekcję bakteryjną lub rzęsistkowicę."]},
                {"h": "Wydzielina różowa i brązowa",
                 "p": ["Różowy lub brązowy odcień oznacza domieszkę krwi. Może pojawić się przy plamieniu owulacyjnym, na kilka dni przed okresem, po współżyciu lub na początku miesiączki. Brązowa wydzielina pod koniec okresu to po prostu dłużej utleniona krew — zwykle nie jest powodem do niepokoju."]},
                {"h": "Zapach",
                 "p": ["Łagodny, „cielisty” zapach jest naturalny. Wyraźny rybi lub gnilny zapach, nasilający się po współżyciu, bywa oznaką bakteryjnej waginozy. Każda zmiana zapachu wraz z innymi objawami to dobry powód do wizyty."]},
                {"h": "Objawy mogące sugerować infekcję",
                 "ul": ["Świąd, pieczenie lub ból okolic intymnych",
                        "Wyraźnie zmieniona barwa (zielona, szaro-żółta)",
                        "Nieprzyjemny, rybi zapach",
                        "Pienista lub serowata konsystencja",
                        "Ból lub dyskomfort przy oddawaniu moczu",
                        "Ból w dole brzucha"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Wydzielina naturalnie zmienia się w trakcie cyklu — to nie objaw choroby",
                               "Nie należy stosować irygacji ani silnych środków myjących „wewnątrz”",
                               "Probiotyki i higiena pomagają, ale nie leczą infekcji"]},
            "remember": ["Przezroczysta i biała wydzielina bez zapachu = norma",
                         "Kolor + zapach + świąd razem sugerują infekcję",
                         "Nie lecz się na własną rękę — potrzebne jest badanie ginekologiczne"],
            "doctor": ["Zielona lub szara wydzielina z nieprzyjemnym zapachem",
                       "Świąd i pieczenie utrzymujące się ponad kilka dni",
                       "Wydzielina z krwią poza miesiączką, zwłaszcza po menopauzie"],
            "summary": "Kolor wydzieliny sam w sobie rzadko bywa problemem — liczy się całość: konsystencja, zapach i towarzyszące objawy. Fizjologiczne zmiany są zdrowe, a niepokojące objawy najlepiej skonsultować z ginekologiem."
        },
    },
    {
        "slug": "wydzielina-w-fazach",
        "title": "Wydzielina w różnych fazach cyklu",
        "category": "Zdrowie reprodukcyjne",
        "summary": "Jak śluz szyjkowy zmienia się w trakcie cyklu i jak obserwować go jako naturalny wskaźnik płodności.",
        "intro": "Śluz szyjkowy to darmowy, dostępny na wyciągnięcie ręki wskaźnik tego, co dzieje się w Twoich hormonach. Warto nauczyć się go czytać.",
        "read_minutes": 5,
        "illustration": "bloom",
        "tone": "peach",
        "badge": "",
        "phase": "ovulation",
        "keywords": "śluz, wydzielina, fazy cyklu, owulacja, płodność, estrogen",
        "related": ["kolor-wydzieliny", "jak-rozpoznac-owulacje", "cztery-fazy"],
        "content": {
            "sections": [
                {"h": "Po okresie — sucho",
                 "p": ["Przez kilka dni po miesiączce wydzieliny jest mało lub nie ma jej wcale. Szyjka jest zamknięta, a śluz gęsty i nieprzepuszczalny. To faza, w której zajście w ciążę jest mało prawdopodobne."]},
                {"h": "W fazie folikularnej — kleisty i kremowy",
                 "p": ["Wraz ze wzrostem estrogenu śluz staje się mętny, kleisty, a potem kremowy. Jego rola to ułatwianie przemieszczania się plemników. Pojawienie się kremowego śluzu zwykle zapowiada zbliżającą się owulację."]},
                {"h": "Przed owulacją — śliski i rozciągliwy",
                 "p": ["Szczyt płodności poznasz po śluzie przypominającym surowe białko jajka: przezroczystym, śliskim i rozciągającym się między palcami. To moment największej płodności w cyklu."]},
                {"h": "Po owulacji — gęstnieje",
                 "p": ["Po owulacji progesteron powoduje, że śluz robi się gęsty, kleisty i mętny, a szyjka znów się zamyka. Część kobiet zauważa też krótkie, delikatne plamienie owulacyjne."]},
                {"h": "Jak obserwować śluz",
                 "ul": ["Sprawdzaj konsystencję przy okazji korzystania z toalety",
                        "Zwracaj uwagę na rozciągliwość między kciukiem a palcem",
                        "Notuj wynik codziennie w Dzienniku Cyklii",
                        "Nie oceniaj po wydzielinie po współżyciu — łatwo ją pomylić"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Śluz to efekt działania estrogenu — im bliżej owulacji, tym bardziej „przyjazny” dla plemników",
                               "Łączenie obserwacji śluzu z kalendarzem zwiększa trafność prognozy",
                               "Przy tabletkach antykoncepcyjnych śluz nie daje wiarygodnych sygnałów"]},
            "remember": ["Sucho → kleisto → kremowo → ślisko (szczyt) → gęsto",
                         "Rozciągliwy śluz „białka jajka” to sygnał zbliżającej się owulacji",
                         "Zapisuj obserwacje codziennie — to najskuteczniejsza metoda"],
            "doctor": ["Śluz o nieprzyjemnym zapachu lub zielonej barwie",
                       "Silny świąd lub pieczenie w trakcie cyklu",
                       "Krwisty śluz poza okresem, zwłaszcza nawracający"],
            "summary": "Śluz szyjkowy to naturalny, cykliczny wskaźnik zmian hormonalnych. Obserwowany systematycznie pomaga zrozumieć własny cykl, ale nie powinien być traktowany jako pewna metoda antykoncepcji."
        },
    },
    {
        "slug": "plamienie-czy-okres",
        "title": "Plamienie czy okres — jak rozpoznać różnicę?",
        "category": "Zdrowie reprodukcyjne",
        "summary": "Delikatne plamienie a pełna miesiączka — jak odróżnić krwawienie implantacyjne, owulacyjne i plamienie przed okresem.",
        "intro": "Nie każde krwawienie to miesiączka. Plamienia w środku cyklu czy przed okresem są częste i zwykle niegroźne, ale warto wiedzieć, co mogą oznaczać.",
        "read_minutes": 6,
        "illustration": "spotting",
        "tone": "blue",
        "badge": "",
        "phase": "pre_period",
        "keywords": "plamienie, krwawienie, okres, implantacja, owulacja, brązowa wydzielina",
        "related": ["kolor-wydzieliny", "wczesne-objawy-ciazy", "skrzepy"],
        "content": {
            "sections": [
                {"h": "Czym różni się plamienie od okresu?",
                 "p": ["Miesiączka to krwawienie trwające zwykle 3–7 dni, na tyle obfite, że wymaga podpaski lub tamponu. Plamienie to delikatna, brązowa lub różowa wydzielina z krwią, która zwykle nie wymaga zabezpieczenia lub tylko podpaski dziennej."]},
                {"h": "Plamienie owulacyjne",
                 "p": ["Kilka kropel różowej lub brązowej wydzieliny w okolicy połowy cyklu to często plamienie owulacyjne — efekt krótkiego spadku estrogenu przy uwolnieniu komórki jajowej."]},
                {"h": "Plamienie przed okresem",
                 "p": ["Brązowe plamienie na 1–2 dni przed miesiączką to dłużej utleniona krew, która wypływa powoli. To normalny początek okresu u wielu kobiet i nie ma się czym martwić."]},
                {"h": "Krwawienie implantacyjne",
                 "p": ["Jeśli doszło do zapłodnienia, małe plamienie może pojawić się około 6–12 dni po owulacji, gdy zarodek zagnieżdża się w macicy. Jest zwykle bardzo skąpe, krótkie i nie narasta."]},
                {"h": "Plamienie przy tabletkach",
                 "p": ["W pierwszych miesiącach stosowania antykoncepcji hormonalnej (zwłaszcza tabletek ciągłych) plamienia są częste. To naturalna adaptacja organizmu — o ile nie są obfite i nie towarzyszy im ból."]},
                {"h": "Kiedy może być objawem problemu",
                 "ul": ["Plamienie po współżyciu",
                        "Plamienie w środku cyklu nawracające co miesiąc",
                        "Krwawienie między okresami przy regularnej miesiączce",
                        "Plamienie w ciąży lub po menopauzie"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Brązowa wydzielina = krew, która zdążyła się utlenić — zwykle oznacza wolniejsze, skąpsze krwawienie",
                               "Pojedyncze plamienie w środku cyklu nie jest niczym niezwykłym",
                               "W Cyklii możesz odnotować okres, nawet jeśli zaczyna się od plamienia"]},
            "remember": ["Plamienie ≠ okres — zwykle jest skąpe i nie wymaga mocnego zabezpieczenia",
                         "Plamienie owulacyjne i przedokresowe to norma",
                         "Nawracające lub pozaseksualne krwawienia warto skonsultować"],
            "doctor": ["Krwawienie między okresami utrzymujące się kilka cykli",
                       "Plamienie po współżyciu, zwłaszcza powtarzające się",
                       "Krwawe upławy po menopauzie — zawsze wymagają konsultacji"],
            "summary": "Plamienie bywa zwykłą fizjologią cyklu, ale też pierwszym sygnałem ciąży lub problemów. Obserwuj je w Cyklii: jeśli się powtarza albo towarzyszy mu ból, zgłoś się do ginekologa."
        },
    },
    {
        "slug": "higiena-intymna",
        "title": "Jak prawidłowo dbać o higienę intymną?",
        "category": "Zdrowie reprodukcyjne",
        "summary": "Delikatna pielęgnacja stref intymnych: co robić, czego unikać i dlaczego „nadmierna higiena” bywa szkodliwa.",
        "intro": "Higiena intymna to przede wszystkim nie przeszkadzanie. Pochwa potrafi zadbać o siebie sama — Twoim zadaniem jest wspierać ją, a nie „czyścić na siłę”.",
        "read_minutes": 5,
        "illustration": "hygiene",
        "tone": "blue",
        "badge": "Poradnik",
        "phase": "any",
        "keywords": "higiena, intymna, mycie, probiotyki, mikrobiota, pielęgnacja",
        "related": ["kolor-wydzieliny", "seks-podczas-okresu", "suchosc"],
        "content": {
            "sections": [
                {"h": "Mycie — delikatnie i z zewnątrz",
                 "p": ["Wystarczy myć zewnętrzne okolice ciepłą wodą lub łagodnym żelem do higieny intymnej o pH zbliżonym do naturalnego. Unikaj zwykłych mydeł z zapachami i środków antybakteryjnych — niszczą naturalną florę."]},
                {"h": "Czego unikać",
                 "ul": ["Irygacji pochwy (tzw. płukanek wewnętrznych)",
                        "Mydła w kostce z silnymi detergentami",
                        "Podpachowych płynów i mgiełek",
                        "Mokrej bielizny i zbyt ciasnej odzieży z tworzyw",
                        "Współżycia przy objawach infekcji"]},
                {"h": "Podczas okresu",
                 "p": ["Zmieniaj podpaskę lub tampon co 4–8 godzin, a kubeczek co 6–12 godzin. Myj okolice częściej, ale nadal delikatnie. W Dzienniku Cyklii możesz śledzić, czy częstotliwość zmian jest odpowiednia."]},
                {"h": "Bielizna i ubrania",
                 "p": ["Bawełniana, przewiewna bielizna pomaga utrzymać suchość. Unikaj spania w syntetycznych legginsach po treningu — mokro i ciepło sprzyja infekcjom grzybicznym."]},
                {"h": "Flora bakteryjna i probiotyki",
                 "p": ["Lactobacillus chroni pochwę przed patogenami. Wspierają go fermentowane produkty, a przy skłonności do nawracających infekcji — probiotyki ginekologiczne (dobrane z lekarzem)."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Pochwa oczyszcza się sama — irygacja zwiększa ryzyko infekcji",
                               "pH okolic intymnych jest kwaśne (3,8–4,5) — mydła alkaliczne je zaburzają",
                               "Nadmierna higiena powoduje podrażnienia częściej niż jej brak"]},
            "remember": ["Myj z zewnątrz, ciepłą wodą lub żelem intymnym",
                         "Bawełniana bielizna + suchość = zdrowe środowisko",
                         "Probiotyki z diety wspierają naturalną florę"],
            "doctor": ["Utrzymujący się świąd, pieczenie lub zmieniona wydzielina",
                       "Nawracające infekcje mimo właściwej higieny",
                       "Podrażnienie nieustępujące po zmianie kosmetyków"],
            "summary": "Dobrej higienie intymnej sprzyja przede wszystkim umiar: łagodne mycie zewnętrzne, przewiewna bielizna i cierpliwość do naturalnych zapachów. Przy nawracających objawach — ginekolog, nie kolejny antybakteryjny żel."
        },
    },
    {
        "slug": "kiedy-test-ciazowy",
        "title": "Kiedy najlepiej zrobić test ciążowy?",
        "category": "Zdrowie reprodukcyjne",
        "summary": "Termin testu, wiarygodność wyniku, testy paskowe i cyfrowe — praktyczny przewodnik bez niepotrzebnego stresu.",
        "intro": "Zbyt wczesny test to najczęstsza przyczyna fałszywie ujemnego wyniku. Poznaj zasady, które oszczędzą Ci nerwów.",
        "read_minutes": 5,
        "illustration": "test",
        "tone": "peach",
        "badge": "Poradnik",
        "phase": "any",
        "keywords": "test ciążowy, hCG, wynik, kiedy, termin, miesiączka",
        "related": ["wczesne-objawy-ciazy", "plamienie-czy-okres", "pms"],
        "content": {
            "sections": [
                {"h": "Jak działa test ciążowy?",
                 "p": ["Test wykrywa hormon hCG, który zaczyna być produkowany po zagnieżdżeniu zarodka. Hormon podwaja się co kilkadziesiąt godzin, dlatego kluczowy jest dobry moment — nie odczyt testu."]},
                {"h": "Najlepszy termin: dzień spodziewanej miesiączki",
                 "p": ["Najbardziej wiarygodny wynik uzyskasz w dniu spodziewanej miesiączki lub 1–2 dni po niej. Wtedy stężenie hCG jest już wystarczające, by wykrył je prawie każdy test."]},
                {"h": "Testy bardzo wczesne (czułe)",
                 "p": ["Testy oznaczone jako „4–6 dni przed terminem” potrafią wykryć ciążę wcześniej, ale ryzyko wyniku fałszywie ujemnego jest większe. Jeśli chcesz pewności — przetestuj ponownie po kilku dniach."]},
                {"h": "Jak wykonać test, by wynik był wiarygodny",
                 "ul": ["Zrób test rano, z pierwszego moczu (największe stężenie hCG)",
                        "Sprawdź datę ważności testu",
                        "Przeczytaj instrukcję — czas odczytu jest ważny",
                        "Przy wyniku ujemnym, ale brakującej miesiączce — powtórz test po 2–3 dniach"]},
                {"h": "Wynik słabo pozytywny",
                 "p": ["Nawet blada druga kreska przy teście wykonanym prawidłowo zwykle oznacza wynik pozytywny. Dla pewności powtórz test za 2–3 dni — kreska powinna być wyraźniejsza."]},
                {"h": "Wynik pozytywny — co dalej?",
                 "p": ["Umów wizytę u ginekologa. Warto wcześniej zacząć suplementować kwas foliowy (jeśli już go nie bierzesz) i unikać alkoholu. Samopoczucie nie decyduje o wyniku — liczy się badanie."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["hCG pojawia się dopiero po zagnieżdżeniu — wcześniejszy test może być fałszywie ujemny",
                               "Test rano, z porannego moczu, jest najbardziej czuły",
                               "Rzadkie fałszywie dodatnie wyniki zdarzają się przy niektórych lekach i chorobach"]},
            "remember": ["Optymalny termin: dzień spodziewanej miesiączki lub później",
                         "Ujemny wynik + brak okresu = powtórz test za 2–3 dni",
                         "Każda wyraźna druga kreska liczy się jako pozytywna"],
            "doctor": ["Pozytywny wynik — umów wizytę u ginekologa",
                       "Bolesne krwawienie przy pozytywnym teście",
                       "Brak miesiączki przez długi czas i wielokrotnie ujemne testy"],
            "summary": "Test ciążowy jest wiarygodny, jeśli dasz mu szansę: wykonaj go w dniu spodziewanej miesiączki lub później, rano, zgodnie z instrukcją. A jeśli wynik jest pozytywny — po prostu umów wizytę u lekarza."
        },
    },

    # ============================================================
    # SEKS I INTYMNOŚĆ
    # ============================================================
    {
        "slug": "libido-a-cykl",
        "title": "Libido a cykl menstruacyjny",
        "category": "Seks i intymność",
        "summary": "Dlaczego ochota na seks zmienia się w trakcie cyklu i kiedy jest naturalnie najwyższa.",
        "intro": "To nie wyobraźnia — popęd seksualny faktycznie bywa najwyższy tuż przed owulacją. Hormony mają w tym duży udział, ale to tylko część układanki.",
        "read_minutes": 5,
        "illustration": "libido",
        "tone": "pink",
        "badge": "Dla Ciebie",
        "phase": "any",
        "keywords": "libido, ochota, seks, owulacja, estrogen, testosteron, cykl",
        "related": ["seks-a-owulacja", "stres-a-libido", "podczas-owulacji"],
        "content": {
            "sections": [
                {"h": "Hormony i libido",
                 "p": ["Wzrost estrogenu w fazie folikularnej poprawia nastrój, ukrwienie i wrażliwość — wiele kobiet czuje wtedy większą ochotę na bliskość. Po owulacji progesteron działa łagodząco i potrafi obniżać libido."]},
                {"h": "Szczyt w okolicy owulacji",
                 "p": ["Tuż przed owulacją natura zwiększa płodność i zainteresowanie seksem. To biologiczny mechanizm wspierający prokreację — nie oznacza, że zawsze musi się tak układać."]},
                {"h": "Wahania w trakcie cyklu",
                 "ul": ["Faza folikularna i owulacyjna: często najwyższe libido",
                        "Faza lutealna: zmienne — u niektórych niższe, u innych wzmożone",
                        "Przy tabletkach hormonalnych ochota bywa bardziej wyrównana",
                        "Nie ma jednego „właściwego” wzorca"]},
                {"h": "Libido a nastrój i zmęczenie",
                 "p": ["Na ochotę wpływają też stres, sen, samoocena i relacja. Słaby tydzień nie przekreśla Twojej seksualności — to zwykła zmienność, którą można śledzić w dzienniku nastrojów."]},
                {"h": "Kiedy zmiana libido jest problemem?",
                 "p": ["Jeśli spadek ochoty utrzymuje się miesiącami, towarzyszy mu suchość pochwy albo zaburza związek, warto porozmawiać z ginekologiem lub seksuologiem. To częsty temat — nie ma w nim nic wstydliwego."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Naturalny szczyt libido przypada zwykle tuż przed owulacją",
                               "Libido nie musi być stałe — wahania są normalne",
                               "Antykoncepcja hormonalna zmienia naturalny rytm ochoty"]},
            "remember": ["Większa ochota przed owulacją to fizjologia, nie „nadmierna” seksualność",
                         "Niska ochota w fazie lutealnej też jest normalna",
                         "Słuchaj siebie, a nie oczekiwań czy trendów"],
            "doctor": ["Utrzymujący się spadek libido z suchością pochwy",
                       "Ból podczas stosunku",
                       "Problemy z libido wpływające na jakość życia"],
            "summary": "Libido płynie w rytmie hormonów, ale towarzyszą mu też nastrój, sen i relacja. Obserwuj swoje wzorce w Cyklii i traktuj je jak informację o sobie, nie jak wskaźnik „poprawności”."
        },
    },
    {
        "slug": "seks-podczas-okresu",
        "title": "Czy seks podczas okresu jest bezpieczny?",
        "category": "Seks i intymność",
        "summary": "Fakty na temat współżycia w trakcie miesiączki: ryzyko ciąży, higiena i komunikacja z partnerem.",
        "intro": "Seks podczas okresu nie jest ani zabroniony, ani „brudny” — bywa po prostu kwestią wygody i otwartości obu stron.",
        "read_minutes": 4,
        "illustration": "period",
        "tone": "pink",
        "badge": "",
        "phase": "period",
        "keywords": "seks, okres, miesiączka, bezpieczeństwo, ryzyko, ciąży, higiena",
        "related": ["libido-a-cykl", "bezpieczny-seks", "higiena-intymna"],
        "content": {
            "sections": [
                {"h": "Czy seks podczas okresu jest bezpieczny?",
                 "p": ["Jest bezpieczny fizycznie, a przy stosowaniu zabezpieczenia nie zwiększa ryzyka ciąży ani większości infekcji. Kwestie komfortu i estetyki zależą od preferencji obojga partnerów."]},
                {"h": "Ryzyko ciąży",
                 "p": ["Jest niższe niż w okolicy owulacji, ale nie zerowe — plemniki potrafią przeżyć w organizmie kilka dni, a cykl bywa krótszy, niż się wydaje. Jeśli chcesz uniknąć ciąży, zabezpieczaj się tak samo jak zawsze."]},
                {"h": "Higiena i komfort",
                 "ul": ["Można ułatwić sobie sprawę ręcznikiem ciemnego koloru",
                        "Tampon lub kubeczek trzeba usunąć przed stosunkiem",
                        "Wygodny bywa seks w prysznicu",
                        "Nie ma medycznego powodu, by rezygnować — to wybór estetyczny"]},
                {"h": "Infekcje przenoszone drogą płciową",
                 "p": ["Krew nie zwiększa ryzyka STI, ale kontakt z krwią i błonami śluzowymi wymaga szczególnej higieny. Prezerwatywa chroni przed infekcjami tak samo jak w innych dniach cyklu."]},
                {"h": "Komunikacja",
                 "p": ["Najważniejsza jest zgoda i komfort. Rozmowa o tym, co jest dla Ciebie wygodne, buduje bliskość. „Nie w tym tygodniu” zawsze jest w porządku i nie wymaga tłumaczenia."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Ciąża w trakcie okresu jest mało prawdopodobna, ale możliwa",
                               "Prezerwatywa działa tak samo skutecznie w każdym dniu cyklu",
                               "Wiele par czuje wtedy większą wilgotność — to może ułatwiać stosunek"]},
            "remember": ["Usuń tampon lub kubeczek przed stosunkiem",
                         "Zabezpieczenie obowiązuje jak zawsze",
                         "Decyzję podejmujcie wspólnie, bez presji"],
            "doctor": ["Obfite krwawienie podczas stosunku",
                       "Ból w trakcie lub po współżyciu w okresie",
                       "Niepokojące upławy po okresie"],
            "summary": "Seks podczas okresu to normalna, osobista decyzja — bezpieczny przy higienie i zabezpieczeniu. Ważne, by oboje czuli się komfortowo i mogli o tym otwarcie porozmawiać."
        },
    },
    {
        "slug": "rozmowa-o-seksie",
        "title": "Jak rozmawiać z partnerem o seksie?",
        "category": "Seks i intymność",
        "summary": "Jak bez skrępowania mówić o potrzebach, granicach i przyjemności — praktyczne wskazówki do budowania bliskości.",
        "intro": "Dobra rozmowa o seksie to umiejętność, której uczymy się przez całe życie. Zaczyna się od zwykłych, codziennych słów i odzwyczjenia się od tematu tabu.",
        "read_minutes": 5,
        "illustration": "talk",
        "tone": "peach",
        "badge": "",
        "phase": "any",
        "keywords": "rozmowa, partner, seks, potrzeby, komunikacja, granice, bliskość",
        "related": ["masturbacja", "orgazm", "komunikacja-potrzeb"],
        "content": {
            "sections": [
                {"h": "Zacznij poza sypialnią",
                 "p": ["Łatwiej rozmawiać o intymności w neutralnym momencie — na spacerze, przy herbacie — niż w trakcie zbliżenia. Spokojny kontekst obniża napięcie i pozwala mówić jaśniej."]},
                {"h": "Mów o sobie, nie o winie",
                 "p": ["Zamiast „zawsze się spieszysz” spróbuj „czuję się lepiej, gdy mamy więcej czasu na siebie”. Komunikaty o własnych potrzebach nie brzmią jak oskarżenie, więc budują porozumienie."]},
                {"h": "Bądź konkretna",
                 "ul": ["Mów, co lubisz: „podoba mi się, gdy…”, „czuję się dobrze, kiedy…”",
                        "Opisuj doznania, nie tylko oceny („wolniej”, „delikatniej”, „tutaj”)",
                        "Pytaj partnera o jego odczucia i potrzeby",
                        "Zaproponuj eksperyment, który nie musi się udać"]},
                {"h": "Granice są ważne",
                 "p": ["Granice nie są odrzuceniem, tylko mapą. Mów wprost, co nie jest dla Ciebie komfortowe, i reaguj, gdy partner przekracza Twoje granice — delikatnie, ale stanowczo."]},
                {"h": "Po kłótni i kryzysie",
                 "p": ["Kryzysy intymne zdarzają się w każdym związku. Jeśli rozmowy nie wystarczają, seksuolog lub psychoterapeuta par pomaga przełamać impas — to zwykła forma dbania o związek."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Rozmowa o seksie obniża napięcie i wzmacnia bliskość",
                               "Otwarte pary nie zgadzają się — one negocjują potrzeby",
                               "Seksuologia to dziedzina medycyny, nie „egzotyka”"]},
            "remember": ["Mów o potrzebach w spokojnym momencie",
                         "Używaj komunikatów o sobie zamiast oskarżeń",
                         "Granice podawaj jasno i łagodnie"],
            "doctor": ["Problem z intymnością wpływający na związek — rozważ rozmowę ze specjalistą",
                       "Ból podczas stosunku wymaga konsultacji ginekologicznej",
                       "Trudności erekcji lub pożądania u partnera — wsparcie medyczne pomaga"],
            "summary": "Świetny seks zaczyna się od słów, nie od pozycji. Rozmawiaj o potrzebach poza sypialnią, mów o sobie i traktuj granice jak coś naturalnego — a intymność przestanie być tematem tabu."
        },
    },
    {
        "slug": "masturbacja",
        "title": "Masturbacja — fakty i mity",
        "category": "Seks i intymność",
        "summary": "Co nauka mówi o masturbacji, jakie są najczęstsze mity i dlaczego to zdrowy element seksualności.",
        "intro": "Masturbacja to naturalny, zdrowy sposób poznawania własnego ciała i przyjemności. Warto oddzielić fakty od krążących mitów.",
        "read_minutes": 4,
        "illustration": "sparkle",
        "tone": "lilac",
        "badge": "",
        "phase": "any",
        "keywords": "masturbacja, mity, fakty, przyjemność, ciało, seksualność",
        "related": ["poznaj-swoje-cialo", "orgazm", "rozmowa-o-seksie"],
        "content": {
            "sections": [
                {"h": "Fakty",
                 "p": ["Masturbacja nie niszczy zdrowia, nie uzależnia i nie wypacza seksualności. Pomaga poznać własne ciało, uczy, co sprawia przyjemność, rozładowuje napięcie i wspiera higienę snu."]},
                {"h": "Najczęstsze mity",
                 "ul": ["„Masturbacja powoduje bezpłodność” — fałsz, nie ma takiego mechanizmu",
                        "„Od masturbacji się roztargniesz” — brak dowodów",
                        "„Masturbacja zastępuje seks w związku” — zwykle ją uzupełnia",
                        "„To oznaka braku partnera” — to po prostu element seksualności"]},
                {"h": "Dlaczego to ważne",
                 "p": ["Zrozumienie własnej przyjemności ułatwia komunikację z partnerem. Wiele kobiet nie osiąga orgazmu wyłącznie podczas stosunku, a wiedza o własnym ciele zmienia to doświadczenie na lepsze."]},
                {"h": "Higiena i umiar",
                 "p": ["Dbaj o czyste ręce i zaufane akcesoria. Umiar to zdrowa zasada jak w każdej aktywności — jeśli masturbacja zaczyna przeszkadzać w życiu codziennym, warto przyjrzeć się temu ze specjalistą."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Masturbacja nie ma udokumentowanych negatywnych skutków zdrowotnych",
                               "Pomaga w redukcji napięcia i lepszym śnie",
                               "To prywatna, naturalna praktyka — bez „norm” częstotliwości"]},
            "remember": ["Mity o masturbacji nie mają oparcia w nauce",
                         "Poznanie ciała poprawia życie intymne w związku",
                         "Higiena i komfort są ważniejsze niż częstotliwość"],
            "doctor": ["Dolegliwości bólowe lub infekcje okolic intymnych",
                       "Kompulsywne zachowania trudne do kontrolowania",
                       "Utrudniające życie poczucie winy lub wstydu"],
            "summary": "Masturbacja to zdrowy element seksualności — pomaga poznać ciało i lepiej komunikować potrzeby. Wstyd wokół niej wynika z mitów, a nie z faktów."
        },
    },
    {
        "slug": "stres-a-libido",
        "title": "Jak stres wpływa na libido?",
        "category": "Seks i intymność",
        "summary": "Mechanizm działania stresu na popęd seksualny i praktyczne sposoby, by odbudować ochotę na bliskość.",
        "intro": "Kortyzol i adrenalina są świetne na ucieczkę przed zagrożeniem, ale fatalne na romantyczny nastrój. Stres to jeden z głównych zabójców libido.",
        "read_minutes": 5,
        "illustration": "stress",
        "tone": "cream",
        "badge": "",
        "phase": "any",
        "keywords": "stres, libido, kortyzol, relaks, seks, ochota, odpoczynek",
        "related": ["libido-a-cykl", "stres-a-cykl", "zmeczenie"],
        "content": {
            "sections": [
                {"h": "Co dzieje się z ciałem",
                 "p": ["Przewlekły stres podnosi poziom kortyzolu, a ten tłumi produkcję hormonów płciowych i ukrwienie narządów. Efekt: mniejsza wrażliwość, suchość pochwy i po prostu brak ochoty."]},
                {"h": "Stres w głowie",
                 "p": ["Natłok myśli o pracy, finansach i obowiązkach utrudnia odprężenie. Nawet gdy ciało odpowiada, głowa „nie pozwala” — to częsta przyczyna obniżonego libido u kobiet."]},
                {"h": "Jak odbudować ochotę",
                 "ul": ["Zadbaj o sen 7–8 godzin — to podstawa równowagi hormonalnej",
                        "Wprowadź ruch, spacer, joga — obniżają kortyzol",
                        "Ogranicz alkohol i kofeinę po południu",
                        "Zaplanuj czas na bliskość bez presji seksu",
                        "Mów partnerowi, co Cię obciąża"]},
                {"h": "Bliskość bez presji",
                 "p": ["Przytulanie, masaż i czułość bez oczekiwania seksu rozładowują napięcie i budują pożądanie. Intymność nie musi być „sprawdzianem” — może być formą odpoczynku."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Kortyzol i hormony płciowe działają „na zasadzie przeciwwagi”",
                               "Seks przy stresie bywa trudniejszy fizycznie (suchość, napięcie)",
                               "Ruch i sen to najskuteczniejsze naturalne metody redukcji stresu"]},
            "remember": ["Stres to fizjologiczny powód spadku libido, nie „wymówka”",
                         "Czułość bez presji odbudowuje ochotę",
                         "Sen i ruch regulują kortyzol naturalnie"],
            "doctor": ["Spadek libido połączony z depresją lub silnym lękiem",
                       "Ból podczas stosunku nasilany przez napięcie",
                       "Gdy stres utrzymuje się miesiącami — wsparcie psychologa pomaga"],
            "summary": "Stres obniża libido przez kortyzol i napięcie psychiczne. Sen, ruch, czułość bez presji i rozmowa z partnerem odbudowują ochotę — a przy przewlekłym stresie warto skorzystać ze wsparcia specjalisty."
        },
    },
    {
        "slug": "bol-podczas-stosunku",
        "title": "Ból podczas stosunku — kiedy warto skonsultować?",
        "category": "Seks i intymność",
        "summary": "Dyspareunia — możliwe przyczyny bólu podczas współżycia i sygnały wymagające wizyty u ginekologa.",
        "intro": "Ból podczas stosunku nie jest czymś, z czym trzeba się godzić. To częsty, lecz trudny do przyznania problem — i zwykle da się go rozwiązać.",
        "read_minutes": 6,
        "illustration": "pain",
        "tone": "rose",
        "badge": "Poradnik",
        "phase": "any",
        "keywords": "ból, stosunek, dyspareunia, suchość, pochwa, endometrioza, leczenie",
        "related": ["suchosc", "seks-podczas-okresu", "poznaj-swoje-cialo"],
        "content": {
            "sections": [
                {"h": "Co oznacza ból podczas stosunku?",
                 "p": ["Ból przy penetracji, w trakcie lub po współżyciu ma swoją fachową nazwę — dyspareunia. Może mieć podłoże fizyczne, hormonalne, mięśniowe lub psychiczne, a często kilka z nich naraz."]},
                {"h": "Przyczyny fizyczne i hormonalne",
                 "ul": ["Suchość pochwy (spadek estrogenu, tabletki, karmienie piersią)",
                        "Infekcje i stany zapalne okolic intymnych",
                        "Napięcie mięśni dna miednicy",
                        "Blizny po porodzie lub zabiegach",
                        "Endometrioza lub mięśniaki",
                        "Skurcz pochwy (waginizm)"]},
                {"h": "Rola nawilżenia i czasu",
                 "p": ["Niewystarczające nawilżenie to najczęstsza prosta przyczyna bólu. Wydłużenie gry wstępnej, żel nawilżający i cierpliwość zmieniają doświadczenie u wielu par. To nie „wina” którejkolwiek ze stron."]},
                {"h": "Kiedy iść do lekarza?",
                 "p": ["Jeśli ból pojawia się regularnie, nasila lub utrudnia życie — umów wizytę. Ginekolog zbada przyczyny, a seksuolog lub fizjoterapeuta uroginekologiczny pomogą w terapii."]},
                {"h": "Co może pomóc od razu",
                 "ul": ["Żel nawilżający na bazie wody",
                        "Więcej czasu na grę wstępną",
                        "Wygodniejsze pozycje z kontrolą głębokości",
                        "Relaksacja i oddech zamiast „musimy dokończyć”"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Ból przy stosunku dotyka nawet 1 na 5 kobiet",
                               "Nie ma sensu go „przezwyciężać” — to sygnał organizmu",
                               "Większość przyczyn da się skutecznie leczyć"]},
            "remember": ["Suchość to najczęstsza prosta przyczyna — nawilżanie pomaga",
                         "Ból nie jest normalną częścią seksu",
                         "Waginizm i endometrioza są uleczalne — nie godź się na cierpienie"],
            "doctor": ["Regularny ból podczas lub po stosunku",
                       "Ból z krwawieniem lub niepokojącymi upławami",
                       "Ból utrzymujący się po zmianie nawilżenia i pozycji"],
            "summary": "Ból podczas stosunku to objaw, nie wyrok. Pomagają nawilżenie, czas i wygodne pozycje, a przy uporczywych dolegliwościach — ginekolog, seksuolog i fizjoterapeuta dna miednicy."
        },
    },

    # ============================================================
    # PODCZAS OKRESU
    # ============================================================
    {
        "slug": "zmniejsz-bol",
        "title": "Jak zmniejszyć ból menstruacyjny?",
        "category": "Podczas okresu",
        "summary": "Sprawdzone sposoby na bolesne miesiączki: ciepło, ruch, dieta i leki przeciwbólowe.",
        "intro": "Skurcze menstruacyjne potrafią wyłączyć z życia na kilka dni. Na szczęście jest kilka prostych, skutecznych sposobów, by ulżyć sobie szybciej.",
        "read_minutes": 5,
        "illustration": "pain",
        "tone": "rose",
        "badge": "Popularne",
        "phase": "period",
        "keywords": "ból, miesiączka, skurcze, termofor, ibuprofen, magnez, sposoby",
        "related": ["skurcze", "co-jesc-podczas-okresu", "termofor"],
        "content": {
            "sections": [
                {"h": "Ciepło na podbrzusze",
                 "p": ["Termofor, ciepły okład lub ciepła kąpiel rozluźniają mięśnie macicy i zmniejszają skurcze. Ciepło to jedna z najskuteczniejszych niefarmakologicznych metod łagodzenia bólu."]},
                {"h": "Ruch — paradoksalnie pomaga",
                 "p": ["Lekki ruch (spacer, rozciąganie, joga) poprawia krążenie i uwalnia endorfiny, czyli naturalne środki przeciwbólowe. Nie musisz „przemęczać się” — wystarczy 20–30 minut umiarkowanej aktywności."]},
                {"h": "Leki przeciwbólowe",
                 "p": ["Ibuprofen lub naproksen (niesteroidowe leki przeciwzapalne) działają na samą przyczynę skurczów — na prostaglandyny. Przyjmuj je zgodnie z ulotką, najlepiej, gdy tylko poczujesz nadchodzący ból. W razie wątpliwości zapytaj farmaceutę lub lekarza."]},
                {"h": "Magnez i witamina B6",
                 "p": ["Magnez rozluźnia mięśnie i bywa pomocny przy skurczach, witamina B6 wspiera równowagę hormonalną. Suplementy działają najlepiej, gdy przyjmuje się je systematycznie, a nie tylko w dniu bólu."]},
                {"h": "Dieta i nawodnienie",
                 "ul": ["Pij dużo wody — odwodnienie nasila skurcze",
                        "Ogranicz sól i kawę, które wzmagają napięcie",
                        "Sięgaj po potrawy bogate w magnez: zielone warzywa, orzechy, kakao",
                        "Herbaty z rumianku, imbiru lub mięty działają rozluźniająco"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Ibuprofen blokuje prostaglandyny — działa na przyczynę, nie tylko objaw",
                               "Ciepło rozluźnia mięśnie macicy skuteczniej niż „przesiedzenie bólu”",
                               "Reguła: ból nieleczony nasila się — zacznij wcześnie"]},
            "remember": ["Ciepło + lekki ruch + woda = pierwsza linia pomocy",
                         "Ibuprofen przyjmuj zgodnie z ulotką, najlepiej wcześnie",
                         "Magnez i B6 pomagają najbardziej przy regularnym stosowaniu"],
            "doctor": ["Ból nieustępujący po lekach przeciwbólowych",
                       "Ból uniemożliwiający funkcjonowanie, pojawiający się co cykl",
                       "Ból z bardzo obfitym krwawieniem lub nudnościami"],
            "summary": "Ból menstruacyjny nie musi rządzić Twoim tygodniem. Ciepło, ruch, magnez i wcześnie podany ibuprofen zwykle wystarczają — a jeśli nie, to znak, że warto pokazać się ginekologowi."
        },
    },
    {
        "slug": "skurcze",
        "title": "Skurcze menstruacyjne — dlaczego powstają?",
        "category": "Podczas okresu",
        "summary": "Co powoduje bolesne skurcze macicy, czym są prostaglandyny i dlaczego u niektórych kobiet ból jest silniejszy.",
        "intro": "Bolesne skurcze to najczęstsza dolegliwość miesiączkowa. Zrozumienie mechanizmu pomaga skuteczniej je łagodzić.",
        "read_minutes": 4,
        "illustration": "cramps",
        "tone": "blue",
        "badge": "",
        "phase": "period",
        "keywords": "skurcze, macica, prostaglandyny, ból, miesiączka, endometrioza",
        "related": ["zmniejsz-bol", "obfity-okres", "skrzepy"],
        "content": {
            "sections": [
                {"h": "Skąd biorą się skurcze?",
                 "p": ["Podczas miesiączki macica kurczy się, by usunąć złuszczającą się błonę śluzową. Za te skurcze odpowiadają prostaglandyny — związki, które powodują również napięcie naczyń i odczuwanie bólu."]},
                {"h": "Dlaczego u części kobiet ból jest silny?",
                 "p": ["Im wyższy poziom prostaglandyn, tym mocniejsze skurcze i silniejszy ból. Część kobiet jest też wrażliwsza na ból, a przewlekły stan zapalny (np. endometrioza) dodatkowo go wzmaga."]},
                {"h": "Skurcze a inne objawy",
                 "p": ["Prostaglandyny wpływają też na jelita — stąd biegunka lub zaparcia w trakcie okresu. Ból może promieniować do pleców i ud, co często opisywane jest jako „ból kręgosłupa”."]},
                {"h": "Kiedy to coś więcej niż skurcze?",
                 "p": ["Jeśli ból jest bardzo silny od pierwszych okresów, nasila się z wiekiem albo nie reaguje na leki, może wskazywać na endometriozę lub mięśniaki. Badanie u ginekologa rozwiewa wątpliwości."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Prostaglandyny to główni sprawcy skurczów — blokuje je ibuprofen",
                               "Skurcze wzmagają stres i napięcie mięśni",
                               "Antykoncepcja hormonalna często zmniejsza bolesne miesiączki"]},
            "remember": ["Skurcze = naturalna praca macicy, ale ich siła może być sygnałem",
                         "Leki przeciwzapalne zwalczają samą przyczynę skurczów",
                         "Silny, narastający ból warto skonsultować"],
            "doctor": ["Ból narastający z cyklu na cykl",
                       "Ból nieustępujący po 2–3 dawkach leku",
                       "Ból utrudniający szkołę, pracę lub sen co miesiąc"],
            "summary": "Skurcze to efekt działania prostaglandyn — naturalny, ale nie musi być dręczący. Zrozumienie przyczyny pozwala skutecznie reagować: ciepłem, lekami i obserwacją, czy ból nie wymaga konsultacji."
        },
    },
    {
        "slug": "obfity-okres",
        "title": "Co może oznaczać bardzo obfity okres?",
        "category": "Podczas okresu",
        "summary": "Jak ocenić, czy krwawienie jest zbyt obfite, jakie mogą być przyczyny i kiedy zgłosić się do lekarza.",
        "intro": "Obfite miesiączki bywają uciążliwe, ale też sygnałem, że warto sprawdzić stan zdrowia. Podpowiadamy, jak je rozpoznać.",
        "read_minutes": 5,
        "illustration": "heavy",
        "tone": "pink",
        "badge": "Poradnik",
        "phase": "period",
        "keywords": "obfity okres, krwawienie, antykoncepcja, mięśniaki, anemia, lekarz",
        "related": ["skrzepy", "skurcze", "zmniejsz-bol"],
        "content": {
            "sections": [
                {"h": "Czym jest obfity okres?",
                 "p": ["Medycznie o obfitym krwawieniu mówimy, gdy wymaga zmiany zabezpieczenia częściej niż co 1–2 godziny, trwa ponad 7 dni lub pojawiają się duże skrzepy. W codziennym życiu „obfity” to taki, który utrudnia funkcjonowanie."]},
                {"h": "Możliwe przyczyny",
                 "ul": ["Zaburzenia hormonalne (np. niedobór progesteronu)",
                        "Mięśniaki macicy lub polipy",
                        "Adenomioza i endometrioza",
                        "Zaburzenia krzepnięcia krwi",
                        "Choroby tarczycy",
                        "Wkładka wewnątrzmaciczna (spiralna)"]},
                {"h": "Konsekwencje — anemia",
                 "p": ["Regularne, obfite krwawienia prowadzą do niedoboru żelaza i anemii: chroniczne zmęczenie, bladość, zawroty głowy. To ważny powód, by nie odkładać wizyty."]},
                {"h": "Jak się przygotować do wizyty?",
                 "p": ["Zapisz w Cyklii długość i obfitość kilku ostatnich okresów oraz towarzyszące objawy. Taka „mapa” pozwala ginekologowi szybciej postawić diagnozę."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Zmiana zabezpieczenia co godzinę lub dwie to sygnał ostrzegawczy",
                               "Obfite okresy + zmęczenie = sprawdź poziom żelaza",
                               "Wiele przyczyn obfitego krwawienia jest uleczalnych"]},
            "remember": ["Obfite = częste zmiany zabezpieczenia + długie krwawienie",
                         "Nie rekompensuj strat żelaza bez badania — wizyta najpierw",
                         "Przygotuj historię cykli przed konsultacją"],
            "doctor": ["Krwawienie wymagające zmiany zabezpieczenia co godzinę",
                       "Okres trwający ponad 7–8 dni",
                       "Zmęczenie, bladość i zawroty głowy przy obfitych okresach"],
            "summary": "Bardzo obfity okres to nie „uroda cyklu”, tylko sygnał do sprawdzenia. Śledź obfitość w Cyklii, a przy częstych zmianach zabezpieczenia i zmęczeniu umów wizytę — większość przyczyn da się skutecznie leczyć."
        },
    },
    {
        "slug": "tampony-czy-kubeczek",
        "title": "Tampony, podpaski czy kubeczek?",
        "category": "Podczas okresu",
        "summary": "Porównanie metod menstruacyjnych: wygoda, koszty, bezpieczeństwo i wpływ na środowisko.",
        "intro": "Wybór zabezpieczenia to kwestia stylu życia, wrażliwości i budżetu. Poznaj zalety każdej metody, by wybrać swoją.",
        "read_minutes": 5,
        "illustration": "products",
        "tone": "lilac",
        "badge": "",
        "phase": "period",
        "keywords": "tampony, podpaski, kubeczek, majtki menstruacyjne, wybór, ekologia",
        "related": ["higiena-intymna", "co-jesc-podczas-okresu", "obfity-okres"],
        "content": {
            "sections": [
                {"h": "Podpaski",
                 "p": ["Najbardziej dostępne, bezpieczne na noc i łatwe w użyciu. Minus: czuć je, wymagają częstszej zmiany i generują dużo odpadów. Dobre na początek i przy skąpych krwawieniach."]},
                {"h": "Tampony",
                 "p": ["Dyskretne, nie przeszkadzają przy sporcie i pływaniu. Wymagają zmiany co 4–8 godzin, a przy najobfitszych dniach bywają niewystarczające. Warto wybierać tampony bez wybielaczy."]},
                {"h": "Kubeczek menstruacyjny",
                 "p": ["Silikonowy kubeczek zbiera krew, nie chłonie jej. Wystarcza na 6–12 godzin, zużywa się przez lata — oszczędny i ekologiczny. Wymaga odrobiny wprawy i mycia pod bieżącą wodą."]},
                {"h": "Majtki menstruacyjne i dyski",
                 "p": ["Majtki chłonne świetnie sprawdzają się nocą i jako ochrona „zapasowa”. Dyski menstruacyjne łączą wygodę kubeczka z łatwiejszym zakładaniem, a niektóre pozwalają na seks podczas okresu."]},
                {"h": "Jak wybrać?",
                 "ul": ["Testuj różne metody po jednej w spokojniejsze dni",
                        "Na cięższe noce sprawdź podpaskę lub majtki chłonne",
                        "Na pływanie i sport — tampon, kubeczek lub dysk",
                        "Nie musisz wybierać raz na zawsze — metody można łączyć"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Kubeczek i dysk generują najmniej odpadów i kosztują najmniej w przeliczeniu na lata",
                               "Tampon zmieniaj co 4–8 godzin — dłuższe noszenie zwiększa ryzyko TSS",
                               "Metody wielorazowe wymagają dobrego mycia rąk i akcesoriów"]},
            "remember": ["Nie ma jednej „najlepszej” metody — jest ta dla Ciebie",
                         "Tampon: max 8 godzin, kubeczek: 6–12 godzin",
                         "Testuj stopniowo, najlepiej w lżejsze dni okresu"],
            "doctor": ["Pieczenie, świąd lub podrażnienie po nowej metodzie",
                       "Objawy grypopodobne przy założonym tamponie (ryzyko TSS)",
                       "Trudność z usunięciem kubeczka — idź do ginekologa, nie panikuj"],
            "summary": "Podpaski, tampony, kubeczek i majtki chłonne to sprawdzone opcje o różnych kosztach i wygodzie. Najlepsza metoda to ta, która pasuje do Twojego trybu życia — śmiało łącz i eksperymentuj."
        },
    },
    {
        "slug": "cwiczenia-podczas-okresu",
        "title": "Czy można ćwiczyć podczas okresu?",
        "category": "Podczas okresu",
        "summary": "Ruch podczas miesiączki — jak ćwiczyć, by łagodzić ból i poprawić samopoczucie, a kiedy dać sobie odpocząć.",
        "intro": "Tak, można i często warto — umiarkowany ruch łagodzi skurcze i poprawia nastrój. Klucz to słuchanie własnego ciała.",
        "read_minutes": 4,
        "illustration": "sport",
        "tone": "mint",
        "badge": "Dla Ciebie",
        "phase": "period",
        "keywords": "ćwiczenia, sport, okres, miesiączka, trening, joga, spacer",
        "related": ["zmniejsz-bol", "co-jesc-podczas-okresu", "cykl-a-trening"],
        "content": {
            "sections": [
                {"h": "Czy trening w okresie zaszkodzi?",
                 "p": ["Nie. Umiarkowana aktywność nie nasila krwawienia ani nie szkodzi zdrowiu. Wręcz przeciwnie — endorfiny wydzielane podczas ruchu działają przeciwbólowo i poprawiają nastrój."]},
                {"h": "Co ćwiczyć, co odpuścić?",
                 "ul": ["Spacer, joga, pilates, pływanie — świetny wybór",
                        "Lekki trening siłowy o mniejszym obciążeniu — ok",
                        "Wyczerpujące interwały i ciężki trening — rozważ odłożenie",
                        "Zawody i ekstremalny wysiłek — nie w najcięższe dni"]},
                {"h": "Dlaczego bywa trudniej?",
                 "p": ["W pierwsze dni okresu poziom żelaza spada, a progesteron obniża wydolność. Zmęczenie i skurcze sprawiają, że trening bywa mniej efektywny — to normalne, nie powód do frustracji."]},
                {"h": "Wskazówki praktyczne",
                 "p": ["Wybierz tampon, kubeczek lub dysk, który nie przeszkadza w ruchu. Rozgrzewka i nawodnienie są ważniejsze niż zwykle. A jeśli czujesz, że dziś nie dasz rady — spacer też się liczy."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Ruch łagodzi ból dzięki endorfinom — naturalnym środkom przeciwbólowym",
                               "Spadek wydolności w pierwsze dni okresu jest fizjologiczny",
                               "Nawodnienie i żelazo (zielone warzywa, buraki) wspierają trening"]},
            "remember": ["Lekki ruch = mniej skurczów i lepszy nastrój",
                         "Ciężki trening możesz przełożyć o 1–2 dni",
                         "Słuchaj ciała — „dziś nie” też jest odpowiedzią"],
            "doctor": ["Ból uniemożliwiający jakikolwiek ruch",
                       "Zawroty głowy przy wysiłku w okresie",
                       "Silne krwawienie nasilające się po treningu"],
            "summary": "Ćwiczyć podczas okresu można i warto — lekkie formy ruchu łagodzą skurcze. W ciężkie dni daj sobie prawo do odpoczynku, a przy dużych dolegliwościach skonsultuj ból z lekarzem."
        },
    },
    {
        "slug": "co-jesc-podczas-okresu",
        "title": "Co jeść podczas miesiączki?",
        "category": "Podczas okresu",
        "summary": "Żelazo, magnez i nawodnienie — dieta wspierająca organizm w trakcie okresu i łagodząca dolegliwości.",
        "intro": "W trakcie okresu organizm traci żelazo i potrzebuje więcej energii. Kilka prostych zasad sprawi, że ten tydzień będzie lżejszy.",
        "read_minutes": 5,
        "illustration": "food",
        "tone": "cream",
        "badge": "Dla Ciebie",
        "phase": "period",
        "keywords": "jedzenie, dieta, miesiączka, żelazo, magnez, woda, skurcze",
        "related": ["zmniejsz-bol", "ochota-na-slodycze", "cykl-a-apetyt"],
        "content": {
            "sections": [
                {"h": "Żelazo — uzupełnij straty",
                 "p": ["Podczas miesiączki tracisz żelazo wraz z krwią. Włącz do diety zielone warzywa liściaste, strączki, buraki, mięso lub jajka, a obok nich źródła witaminy C (cytrusy, papryka), która poprawia wchłanianie."]},
                {"h": "Magnez na skurcze",
                 "p": ["Magnez rozluźnia mięśnie i łagodzi skurcze oraz napięcie. Znajdziesz go w orzechach, pestkach dyni, kakao, bananach i zielonych warzywach. Ciepłe kakao w okresie to nie tylko przyjemność — to magnez."]},
                {"h": "Nawodnienie",
                 "p": ["Woda zmniejsza wzdęcia i łagodzi bóle głowy. Pij regularnie, a herbaty z rumianku i imbiru działają dodatkowo rozluźniająco. Ogranicz kawę i sól, które wzmagają napięcie i zatrzymanie wody."]},
                {"h": "Co ograniczyć?",
                 "ul": ["Kofeina — nasila skurcze i napięcie",
                        "Sól — potęguje wzdęcia",
                        "Cukier prosty — daje chwilowy zastrzyk energii i gwałtowny spadek",
                        "Tłuste, ciężkie potrawy — mogą nasilać dolegliwości żołądkowe"]},
                {"h": "Mniejsze posiłki, częściej",
                 "p": ["Regularne, mniejsze porcje stabilizują cukier i energię. Jeśli masz ochotę na coś słodkiego, sięgnij po gorzką czekoladę — magnez i kakao zadowolą kubki smakowe i ciało."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Strata żelaza w okresie to ok. 15–30 mg — warto je uzupełniać",
                               "Witamina C zwiększa wchłanianie żelaza z roślin",
                               "Kakao zawiera magnez i wspiera nastrój"]},
            "remember": ["Zielone warzywa + strączki + buraki = żelazo",
                         "Orzechy, pestki, kakao = magnez na skurcze",
                         "Woda i mniejsze posiłki = mniej wzdęć"],
            "doctor": ["Przy obfitych okresach i przewlekłym zmęczeniu sprawdź poziom żelaza",
                       "Silny apetyt lub awersja do jedzenia utrzymująca się po okresie",
                       "Ból żołądka nasilający się po posiłkach"],
            "summary": "W trakcie okresu postaw na żelazo, magnez i wodę, a ogranicz sól, kofeinę i cukier. Drobne zmiany w talerzu realnie zmniejszają skurcze i wzdęcia — a przy obfitych miesiączkach zbadaj poziom żelaza."
        },
    },

    # ============================================================
    # POZNAJ SWÓJ CYKL
    # ============================================================
    {
        "slug": "cztery-fazy",
        "title": "4 fazy cyklu menstruacyjnego",
        "category": "Poznaj swój cykl",
        "summary": "Menstruacja, faza folikularna, owulacja i faza lutealna — co dzieje się w Twoim ciele w każdej z nich.",
        "intro": "Cykl to nie tylko miesiączka — to cztery etapy rządzone przez hormony, które wpływają na energię, nastrój i ciało.",
        "read_minutes": 5,
        "illustration": "phases",
        "tone": "pink",
        "badge": "",
        "phase": "any",
        "keywords": "fazy cyklu, menstruacja, folikularna, owulacja, lutealna, hormony",
        "related": ["faza-folikularna", "faza-lutealna", "podczas-owulacji"],
        "content": {
            "sections": [
                {"h": "Faza 1 — menstruacyjna (dzień 1–5)",
                 "p": ["Cykl zaczyna się w pierwszym dniu miesiączki, gdy macica pozbywa się błony śluzowej. Poziom estrogenu i progesteronu jest najniższy, dlatego energia bywa na minusie — to czas na regenerację."]},
                {"h": "Faza 2 — folikularna (dzień 1–13)",
                 "p": ["Równolegle do miesiączki dojrzewa pęcherzyk z komórką jajową, a poziom estrogenu rośnie. Nastrój i energia wracają, a wiele kobiet czuje się najlepiej w drugiej połowie tej fazy."]},
                {"h": "Faza 3 — owulacyjna (około dnia 14)",
                 "p": ["Dojrzała komórka jajowa zostaje uwolniona. To jedyny dzień w cyklu, w którym zapłodnienie jest możliwe — a okno płodności obejmuje kilka dni przed i dzień po owulacji."]},
                {"h": "Faza 4 — lutealna (dzień 15–28)",
                 "p": ["Po owulacji rośnie progesteron, który przygotowuje macicę na potencjalną ciążę. Gdy do zapłodnienia nie dochodzi, poziom hormonów spada i zaczyna się kolejna miesiączka. W tej fazie pojawiają się objawy PMS."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Faza folikularna i owulacyjna to zwykle czas największej energii",
                               "Faza lutealna bywa trudniejsza: PMS, zmęczenie, wzdęcia",
                               "Długość fazy folikularnej bywa różna, lutealna jest zwykle stała (ok. 14 dni)"]},
            "remember": ["4 fazy: menstruacyjna → folikularna → owulacyjna → lutealna",
                         "Owulacja = jedyny moment zapłodnienia w cyklu",
                         "Cyklię liczysz od 1. dnia miesiączki"],
            "doctor": ["Cykle krótsze niż 21 lub dłuższe niż 35 dni",
                       "Brak owulacji przez wiele cykli (nieregularność + brak okresu)",
                       "Silne objawy PMS utrudniające życie"],
            "summary": "Cykl to rytm czterech faz, w którym hormony sterują energią, nastrojem i płodnością. Zrozumienie ich pozwala planować aktywność i lepiej dbać o siebie każdego dnia."
        },
    },
    {
        "slug": "jak-rozpoznac-owulacje",
        "title": "Jak rozpoznać owulację?",
        "category": "Poznaj swój cykl",
        "summary": "Objawy owulacji, testy owulacyjne, temperatura i śluz — jak wyznaczyć swój dzień płodny.",
        "intro": "Owulacja nie musi być zagadką. Połączenie kilku sygnałów — śluzu, temperatury i objawów — daje całkiem precyzyjny obraz.",
        "read_minutes": 6,
        "illustration": "ovulation",
        "tone": "lilac",
        "badge": "Popularne",
        "phase": "ovulation",
        "keywords": "owulacja, objawy, test owulacyjny, temperatura, śluz, płodność",
        "related": ["podczas-owulacji", "wydzielina-w-fazach", "liczenie-cyklu"],
        "content": {
            "sections": [
                {"h": "Objawy odczuwalne",
                 "ul": ["Zmiana śluzu na śliski, rozciągliwy (jak białko jajka)",
                        "Lekki, kłujący ból w podbrzuszu (ból owulacyjny)",
                        "Delikatne plamienie owulacyjne",
                        "Wzrost libido",
                        "Wrażliwość piersi lub pełność w podbrzuszu"]},
                {"h": "Temperatura bazowa",
                 "p": ["Po owulacji temperatura wzrasta o ok. 0,2–0,5°C i zostaje podwyższona. Mierz ją codziennie rano przed wstaniem z łóżka — skok temperatury potwierdza owulację już po fakcie."]},
                {"h": "Testy owulacyjne (LH)",
                 "p": ["Testy wykrywają wzrost hormonu LH, który poprzedza owulację o 24–36 godzin. To najszybsza metoda na „wyłapanie” terminu — najlepiej zaczynać testowanie kilka dni przed przewidywaną owulacją."]},
                {"h": "Połącz sygnały",
                 "p": ["Kalendarz Cyklii podpowie okno płodności, śluz wskaże kierunek, a temperatura potwierdzi. Im więcej metod połączysz, tym pewniejszy obraz — zwłaszcza przy nieregularnych cyklach."]},
                {"h": "Cykl bez owulacji?",
                 "p": ["Owulacja nie występuje w każdym cyklu — zdarza się zwłaszcza przy stresie, chorobie czy zmianach hormonalnych. Brak wyraźnych sygnałów w jednym miesiącu nie jest powodem do niepokoju."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Owulacja następuje zwykle ok. 14 dni przed końcem cyklu",
                               "Śluz i LH mówią o zbliżającej się owulacji, temperatura — potwierdza ją",
                               "Sygnały owulacji bywają subtelne — warto je notować"]},
            "remember": ["Śluz „białka jajka” + wzrost LH = owulacja blisko",
                         "Skok temperatury potwierdza owulację po fakcie",
                         "Jedna „pusta” owulacja w roku to norma"],
            "doctor": ["Brak jakichkolwiek sygnałów owulacji przez wiele miesięcy",
                       "Nieregularne cykle utrudniające planowanie rodziny",
                       "Ból owulacyjny bardzo silny lub nawracający"],
            "summary": "Owulację rozpoznasz łącząc kalendarz, śluz, temperaturę i ewentualnie testy LH. To przydatna wiedza zarówno przy staraniu się o dziecko, jak i przy rozumieniu własnego ciała."
        },
    },
    {
        "slug": "podczas-owulacji",
        "title": "Co dzieje się podczas owulacji?",
        "category": "Poznaj swój cykl",
        "summary": "Od uwolnienia komórki jajowej po okno płodności — fizjologia owulacji krok po kroku.",
        "intro": "Owulacja to krótki, ale kluczowy moment cyklu. Sprawdź, co dokładnie dzieje się w Twoim ciele w tych kilkudziesięciu godzinach.",
        "read_minutes": 4,
        "illustration": "egg",
        "tone": "lilac",
        "badge": "",
        "phase": "ovulation",
        "keywords": "owulacja, komórka jajowa, jajnik, pęcherzyk, okno płodne, hormony",
        "related": ["jak-rozpoznac-owulacje", "cztery-fazy", "libido-a-cykl"],
        "content": {
            "sections": [
                {"h": "Uwolnienie komórki jajowej",
                 "p": ["Wzrost LH powoduje pęknięcie dojrzałego pęcherzyka w jajniku i uwolnienie komórki jajowej. To właśnie ten moment nazywamy owulacją."]},
                {"h": "Jak długo żyje komórka jajowa?",
                 "p": ["Komórka jajowa jest zdolna do zapłodnienia zaledwie 12–24 godziny po uwolnieniu. Plemniki potrafią jednak przetrwać w organizmie do 5 dni, dlatego okno płodności obejmuje dni przed owulacją."]},
                {"h": "Zmiany w ciele",
                 "ul": ["Śluz staje się śliski i rozciągliwy",
                        "Część kobiet odczuwa lekki ból lub ukłucie w jajniku",
                        "Temperatura zaczyna rosnąć po owulacji",
                        "Libido często wzrasta",
                        "Piersi mogą być pełniejsze"]},
                {"h": "Po owulacji",
                 "p": ["Pęcherzyk przekształca się w ciałko żółte, które produkuje progesteron. Jeśli nie dojdzie do zapłodnienia, po ok. 14 dniach poziom hormonów spada i zaczyna się miesiączka."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Komórka jajowa żyje 12–24 h, ale plemniki — nawet 5 dni",
                               "Okno płodności = ok. 5 dni przed owulacją + 1 dzień po",
                               "Cyklia przewiduje owulację na podstawie Twojej historii okresów"]},
            "remember": ["Owulacja = uwolnienie komórki jajowej z jajnika",
                         "Okno płodności jest dłuższe niż sam dzień owulacji",
                         "Objawy owulacji bywają subtelne i różne u różnych kobiet"],
            "doctor": ["Silny ból w podbrzuszu w środku cyklu, nieustępujący po lekach",
                       "Plamienie owulacyjne z towarzyszącym bólem",
                       "Brak objawów owulacji przez wiele miesięcy przy planowaniu ciąży"],
            "summary": "Owulacja to moment uwolnienia komórki jajowej — krótki, ale kluczowy dla płodności. Warto znać swoje sygnały, bo pozwalają lepiej planować i rozumieć cykl."
        },
    },
    {
        "slug": "faza-lutealna",
        "title": "Faza lutealna — co warto wiedzieć?",
        "category": "Poznaj swój cykl",
        "summary": "Progesteron, PMS, energia i sen w drugiej połowie cyklu — jak przetrwać fazę lutealną z uśmiechem.",
        "intro": "Faza lutealna to druga połowa cyklu, w której progesteron bierze górę. To czas charakterystycznych objawów — ale też świetna okazja, by zwolnić.",
        "read_minutes": 5,
        "illustration": "moon",
        "tone": "blue",
        "badge": "",
        "phase": "luteal",
        "keywords": "faza lutealna, progesteron, PMS, energia, sen, cykl",
        "related": ["cztery-fazy", "pms", "zmeczenie"],
        "content": {
            "sections": [
                {"h": "Co dzieje się w fazie lutealnej?",
                 "p": ["Po owulacji ciałko żółte produkuje progesteron, który przygotowuje macicę na ciążę. Temperatura ciała jest podwyższona, a organizm „pracuje na innych obrotach” niż w pierwszej fazie cyklu."]},
                {"h": "Progesteron a samopoczucie",
                 "ul": ["Możliwe wzdęcia i zatrzymanie wody",
                        "Większa senność i zmęczenie",
                        "Ból i tkliwość piersi",
                        "Wahania nastroju, drażliwość",
                        "Zwiększony apetyt, zwłaszcza na słodycze"]},
                {"h": "Energia w drugiej połowie cyklu",
                 "p": ["Wiele kobiet ma w fazie lutealnej mniej energii na intensywny wysiłek. To dobry czas na lżejsze treningi, stretching i więcej snu — planowanie „pod cykl” poprawia samopoczucie."]},
                {"h": "Jak dbać o siebie?",
                 "p": ["Zadbaj o magnez i witaminę B6, ogranicz kofeinę i sól, śpij regularnie. Łagodny ruch i ciepłe kąpiele rozluźniają. A jeśli objawy są bardzo nasilone, porozmawiaj z lekarzem o PMS i PMDD."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Faza lutealna trwa zwykle 12–14 dni i bywa mniej stała u młodych kobiet",
                               "Progesteron podnosi temperaturę — stąd odczuwane „ciepło”",
                               "Niemal 75% kobiet odczuwa jakieś objawy w tej fazie"]},
            "remember": ["Faza lutealna = progesteron, PMS i spokojniejsze tempo",
                         "Magnez, B6 i sen łagodzą objawy",
                         "Objawy PMS to fizjologia, nie „słabość”"],
            "doctor": ["Bardzo nasilone objawy utrudniające codzienne funkcjonowanie",
                       "Podejrzenie PMDD (ciężka depresja przedmiesiączkowa)",
                       "Znikające objawy miesiączki przy regularnych cyklach"],
            "summary": "Faza lutealna to czas progesteronu i typowych objawów PMS. Traktuj ją jak naturalne „wolniejsze biegi” — lżejszy ruch, więcej snu i magnez zdziałają cuda."
        },
    },
    {
        "slug": "liczenie-cyklu",
        "title": "Jak liczyć długość cyklu?",
        "category": "Poznaj swój cykl",
        "summary": "Od pierwszego dnia okresu do dnia przed kolejną miesiączką — prosta metoda liczenia cyklu krok po kroku.",
        "intro": "Poprawne liczenie cyklu to podstawa wiarygodnych prognoz. Na szczęście to banalnie proste — i Cyklia robi to za Ciebie.",
        "read_minutes": 4,
        "illustration": "calendar",
        "tone": "cream",
        "badge": "Poradnik",
        "phase": "any",
        "keywords": "cykl, liczenie, długość, regularność, kalendarz, miesiączka",
        "related": ["cztery-fazy", "regularny-cykl", "wczesne-objawy-ciazy"],
        "content": {
            "sections": [
                {"h": "Zasada liczenia",
                 "p": ["Cykl liczysz od pierwszego dnia jednej miesiączki do dnia przed pierwszym dniem kolejnej. Czyli jeśli okres zaczyna się 1. i następny 30., cykl trwa 29 dni."]},
                {"h": "Przykład",
                 "ul": ["Okres 1: 1–5 maja",
                        "Okres 2: 29 maja",
                        "Długość cyklu: od 1 maja do 28 maja = 28 dni"]},
                {"h": "Co wpisujesz w Cyklii?",
                 "p": ["Wystarczy zaznaczyć pierwszy i ostatni dzień miesiączki. Aplikacja sama policzy długość cyklu, średnią i regularność, a prognozy stają się dokładniejsze z każdym kolejnym wpisem."]},
                {"h": "Regularność",
                 "p": ["Różnice do 7 dni między cyklami są całkowicie normalne. Cyklię liczymy na podstawie średniej z ostatnich wpisów — im więcej danych, tym trafniejsza prognoza."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Cykl = 1. dzień okresu → dzień przed kolejnym okresem",
                               "Średnia długość to 21–35 dni, nie zawsze „idealne” 28",
                               "Dwa pierwsze lata od pierwszej miesiączki bywają nieregularne"]},
            "remember": ["Zaznaczaj pierwszy dzień okresu zawsze — to podstawa prognozy",
                         "Różnice do 7 dni między cyklami są normą",
                         "Im więcej wpisów, tym lepsze prognozy Cyklii"],
            "doctor": ["Cykle stale krótsze niż 21 lub dłuższe niż 35 dni",
                       "Brak miesiączki przez ponad 3 miesiące",
                       "Duża nieregularność (różnice powyżej 7–9 dni)"],
            "summary": "Liczenie cyklu to proste: od pierwszego dnia okresu do dnia przed następnym. Wpisuj dane do Cyklii, a aplikacja zajmie się resztą — od średniej po prognozę owulacji."
        },
    },
    {
        "slug": "cykl-a-trening",
        "title": "Cykl a trening — jak dopasować aktywność?",
        "category": "Poznaj swój cykl",
        "summary": "Energia, siła i regeneracja zmieniają się w trakcie cyklu — jak planować treningi zgodnie z fazami.",
        "intro": "Twoje ciało nie jest tak samo wydolne przez cały miesiąc. Dopasowanie treningu do faz cyklu poprawia efekty i samopoczucie.",
        "read_minutes": 5,
        "illustration": "training",
        "tone": "blue",
        "badge": "",
        "phase": "any",
        "keywords": "trening, sport, cykl, energia, siła, regeneracja, fazy",
        "related": ["cztery-fazy", "cwiczenia-podczas-okresu", "cykl-a-apetyt"],
        "content": {
            "sections": [
                {"h": "Faza folikularna — energia w górę",
                 "p": ["Rosnący estrogen poprawia wydolność, siłę i regenerację. To świetny czas na intensywniejsze treningi, interwały i progresję obciążeń."]},
                {"h": "W okolicy owulacji — szczyt formy",
                 "p": ["Szczyt siły i koordynacji przypada zwykle wokół owulacji. Jeśli czujesz się świetnie — wykorzystaj to, ale pamiętaj o stabilizacji i rozgrzewce (większe ryzyko kontuzji stawów w tej fazie)."]},
                {"h": "Faza lutealna — zwolnij",
                 "p": ["Progesteron obniża wydolność i podnosi temperaturę ciała. Lżejsze treningi, joga, pływanie i dłuższa regeneracja sprawdzą się lepiej niż rekordy. Nasilenie dolegliwości PMS też bywa mniejsze przy regularnym ruchu."]},
                {"h": "Miesiączka — słuchaj ciała",
                 "p": ["Pierwsze dni okresu bywają najcięższe. Spacery, rozciąganie i lekka aktywność łagodzą skurcze; ciężki trening możesz śmiało przełożyć. Każda odpowiedź organizmu jest dobra."]},
                {"h": "Zasady praktyczne",
                 "ul": ["Śledź energię w dzienniku Cyklii — zauważysz wzorce",
                        "Nie zmuszaj się do intensywności w trudne dni",
                        "Nawodnienie i żelazo w okresie wspierają trening",
                        "Regeneracja to część treningu"]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Estrogen wspiera wydolność, progesteron ją obniża",
                               "W fazie lutealnej ciało pracuje w wyższej temperaturze",
                               "Trening w rytmie cyklu to wybór, nie sztywna reguła"]},
            "remember": ["Folikularna = intensywność, lutealna = regeneracja",
                         "Słuchanie ciała wygrywa z harmonogramem",
                         "Regularny ruch łagodzi PMS"],
            "doctor": ["Ból lub zawroty głowy przy wysiłku",
                       "Bardzo szybkie męczenie się w tej samej fazie co cykl",
                       "Utrata miesiączki przy intensywnych treningach"],
            "summary": "Cykl wpływa na wydolność — estrogen daje energię, progesteron prosi o zwolnienie. Planuj intensywne treningi w pierwszej połowie cyklu, a w drugiej stawiaj na regenerację i łagodny ruch."
        },
    },

    # ============================================================
    # CIAŁO I SAMOPOCZUCIE
    # ============================================================
    {
        "slug": "pms",
        "title": "Czym jest PMS i jak go złagodzić?",
        "category": "Ciało i samopoczucie",
        "summary": "Zespół napięcia przedmiesiączkowego — objawy, przyczyny i skuteczne sposoby łagodzenia PMS.",
        "intro": "PMS to nie „humory do zniesienia” — to realna reakcja hormonalna. Dobra wiadomość: objawy można skutecznie łagodzić.",
        "read_minutes": 6,
        "illustration": "pms",
        "tone": "rose",
        "badge": "Popularne",
        "phase": "pre_period",
        "keywords": "PMS, zespół napięcia przedmiesiączkowego, objawy, magnez, nastrój, PMDD",
        "related": ["wczesne-objawy-ciazy", "bol-piersi", "zmeczenie"],
        "content": {
            "sections": [
                {"h": "Co to jest PMS?",
                 "p": ["Zespół napięcia przedmiesiączkowego to zbiór fizycznych i psychicznych objawów pojawiających się w fazie lutealnej i ustępujących po rozpoczęciu miesiączki. Dotyczy nawet 3 na 4 kobiety w wieku rozrodczym."]},
                {"h": "Najczęstsze objawy",
                 "ul": ["Wahania nastroju i drażliwość",
                        "Ból i tkliwość piersi",
                        "Wzdęcia i zatrzymanie wody",
                        "Zmęczenie i problemy ze snem",
                        "Bóle głowy",
                        "Zwiększony apetyt, ochota na słodycze"]},
                {"h": "Co pomaga?",
                 "ul": ["Ruch 3–4 razy w tygodniu (spacer, joga, pływanie)",
                        "Sen 7–8 godzin o stałych porach",
                        "Magnez i witamina B6",
                        "Ograniczenie kawy, soli i cukru w fazie lutealnej",
                        "Ciepłe okłady i relaksacja"]},
                {"h": "Dziennik objawów",
                 "p": ["Zapisuj objawy w Cyklii — zobaczysz, czy wracają cyklicznie i kiedy. Ta wiedza pomaga przygotować się na trudniejsze dni i jest świetnym materiałem do rozmowy z lekarzem."]},
                {"h": "PMS a PMDD",
                 "p": ["PMDD to ciężka, ułomna odmiana PMS — z depresją, lękiem i myślami samobójczymi w fazie lutealnej. To jednostka chorobowa, którą leczy się skutecznie (terapia hormonalna, antydepresanty, zmiana stylu życia)."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["PMS wiąże się ze spadkiem serotoniny w fazie lutealnej",
                               "Objawy ustępują zwykle w pierwszych dniach miesiączki",
                               "PMDD to choroba, nie „silny PMS” — wymaga leczenia"]},
            "remember": ["PMS jest realny i da się go łagodzić",
                         "Magnez + B6 + ruch + sen = najlepszy zestaw",
                         "Dziennik objawów pomaga przewidzieć trudne dni"],
            "doctor": ["Objawy bardzo nasilone lub utrzymujące się po okresie",
                       "Depresja, lęk lub myśli samobójcze przed miesiączką",
                       "PMS przeszkadzający w pracy, szkole i relacjach"],
            "summary": "PMS to reakcja organizmu na zmiany hormonalne — częsta i uleczalna w swojej uciążliwości. Łagodzą go ruch, sen, magnez i świadomość własnych cykli, a przy PMDD konieczna jest pomoc lekarza."
        },
    },
    {
        "slug": "bol-piersi",
        "title": "Dlaczego piersi bolą przed okresem?",
        "category": "Ciało i samopoczucie",
        "summary": "Mastalgia — bolesność piersi przed miesiączką, jej przyczyny hormonalne i sposoby na ulgę.",
        "intro": "Napięte, pełniejsze i wrażliwe piersi przed okresem to jedna z najczęstszych dolegliwości PMS. Zwykle to fizjologia, nie choroba.",
        "read_minutes": 4,
        "illustration": "breasts",
        "tone": "rose",
        "badge": "Popularne",
        "phase": "pre_period",
        "keywords": "piersi, ból, tkliwość, miesiączka, progesteron, mastalgia",
        "related": ["pms", "wzdęcia", "zmeczenie"],
        "content": {
            "sections": [
                {"h": "Skąd ten ból?",
                 "p": ["W drugiej fazie cyklu progesteron i prolaktyna powodują rozrost gruczołów piersiowych i zatrzymanie wody. Piersi stają się pełniejsze, cięższe i wrażliwe — to cykliczna mastalgia."]},
                {"h": "Kiedy się pojawia?",
                 "p": ["Zwykle 1–2 tygodnie przed miesiączką, z największym natężeniem tuż przed nią. Ustępuje wraz z rozpoczęciem lub w trakcie okresu — to ważny wyróżnik wobec bólu niecyklicznego."]},
                {"h": "Jak złagodzić?",
                 "ul": ["Dobrze dopasowany biustonosz (w tym sportowy na noc)",
                        "Ograniczenie kofeiny i soli",
                        "Magnez i witamina E (skonsultuj suplementację)",
                        "Okłady chłodzące przy tkliwości",
                        "Mniej soli → mniej zatrzymanej wody"]},
                {"h": "Ból niecykliczny",
                 "p": ["Jeśli ból nie zależy od cyklu, dotyczy jednej piersi, pojawia się z guzkiem lub zmianą skórną — wymaga badania ginekologicznego, najlepiej z USG piersi."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Cykliczny ból piersi to efekt hormonów, nie patologia",
                               "Zaburzenia tarczycy mogą nasilać tkliwość piersi",
                               "Zastój wody w fazie lutealnej wzmacnia odczucie napięcia"]},
            "remember": ["Ból piersi przed okresem = fizjologia cyklu",
                         "Dobry biustonosz i mniej soli przynoszą ulgę",
                         "Ból niecykliczny lub z guzkiem wymaga badania"],
            "doctor": ["Ból w jednej piersi, nieustępujący po okresie",
                       "Wyraźny guzek, wciągnięta skóra lub wydzielina z brodawki",
                       "Zmiana piersi odczuwalna w samobadaniu"],
            "summary": "Ból piersi przed okresem to typowy objaw hormonalny, który mija z miesiączką. Pomagają wygodny biustonosz, mniej soli i magnez, a wszelkie zmiany niecykliczne warto pokazać lekarzowi."
        },
    },
    {
        "slug": "wzdęcia",
        "title": "Wzdęcia przed miesiączką",
        "category": "Ciało i samopoczucie",
        "summary": "Dlaczego brzuch puchnie przed okresem, jak go złagodzić dietą i ruchem oraz kiedy wzdęcia wymagają konsultacji.",
        "intro": "Uczucie „balonowego” brzucha przed okresem to progesteron i zatrzymana woda — nie przybranie na wadze.",
        "read_minutes": 4,
        "illustration": "balloon",
        "tone": "pink",
        "badge": "",
        "phase": "pre_period",
        "keywords": "wzdęcia, brzuch, miesiączka, progesteron, woda, dieta",
        "related": ["pms", "ochota-na-slodycze", "cykl-a-apetyt"],
        "content": {
            "sections": [
                {"h": "Dlaczego brzuch puchnie?",
                 "p": ["W fazie lutealnej progesteron spowalnia pracę jelit i sprzyja zatrzymaniu wody. Efekt: uczucie pełności, wzdęcia i napięty brzuch — mimo że na wadze przybyło tylko „powietrza i wody”."]},
                {"h": "Dieta łagodząca wzdęcia",
                 "ul": ["Pij dużo wody — paradoksalnie zmniejsza zatrzymywanie",
                        "Ogranicz sól, słone przekąski i przetworzoną żywność",
                        "Unikaj napojów gazowanych i słodzików",
                        "Postaw na banany, jogurt, imbir, koperek",
                        "Jedz mniejsze, regularne porcje"]},
                {"h": "Ruch i ciepło",
                 "p": ["Spacer i rozciąganie pobudzają perystaltykę, ciepłe okłady rozluźniają mięśnie brzucha. Joga (skręty, pozycja dziecka) bywa zaskakująco skuteczna na wzdęcia."]},
                {"h": "Wzdęcia a waga",
                 "p": ["Przyrost 1–2 kg przed okresem to głównie woda — wraca do normy po miesiączce. Nie oceniaj siebie w tych dniach i nie podejmuj decyzji dietetycznych pod wpływem „balonowego” brzucha."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Zatrzymanie wody w fazie lutealnej dotyka większości kobiet",
                               "Mniej soli działa lepiej niż mniej jedzenia",
                               "Wzdęcia po okresie zwykle ustępują samoistnie"]},
            "remember": ["Wzdęcia ≠ przybranie na wadze",
                         "Woda, mniej soli i spacer to najlepszy zestaw",
                         "Ciepło i joga rozluźniają jelita"],
            "doctor": ["Ból brzucha silniejszy niż wzdęcia",
                       "Wzdęcia z towarzyszącymi zaparciami lub biegunką trwające po okresie",
                       "Nagły, twardy brzuch z bólem"],
            "summary": "Wzdęcia przed okresem to woda i spowolnione jelita pod wpływem progesteronu. Mniej soli, więcej wody, ruch i ciepło wyraźnie pomagają, a po okresie wszystko wraca do normy."
        },
    },
    {
        "slug": "zmeczenie",
        "title": "Zmęczenie przed miesiączką",
        "category": "Ciało i samopoczucie",
        "summary": "Dlaczego w fazie lutealnej brakuje energii, jak odzyskać siły i kiedy zmęczenie wymaga sprawdzenia.",
        "intro": "Senność i spadek energii przed okresem to nie lenistwo — to progesteron, który naturalnie spowalnia organizm.",
        "read_minutes": 4,
        "illustration": "sleepy",
        "tone": "blue",
        "badge": "Dla Ciebie",
        "phase": "pre_period",
        "keywords": "zmęczenie, sen, energia, miesiączka, progesteron, PMS",
        "related": ["pms", "sen-a-hormony", "cykl-a-trening"],
        "content": {
            "sections": [
                {"h": "Skąd bierze się zmęczenie?",
                 "p": ["W fazie lutealnej progesteron działa usypiająco i obniża wydolność. Dodatkowo spadki energii nasilają stres i niedobór magnezu — stąd „guma” przed okresem."]},
                {"h": "Sen przed okresem",
                 "p": ["Zapotrzebowanie na sen w fazie lutealnej bywa większe, a jakość snu niższa (termoregulacja). Jeśli możesz, pozwól sobie na dłuższy sen lub krótką drzemkę — to fizjologia, nie rozleniwienie."]},
                {"h": "Jak odzyskać energię",
                 "ul": ["Ruch na świeżym powietrzu (paradoksalnie dodaje energii)",
                        "Zbilansowane posiłki bogate w białko i magnez",
                        "Krótka drzemka do 20 minut",
                        "Światło słoneczne rano",
                        "Unikanie dosypywania kawy po południu"]},
                {"h": "Kiedy to coś więcej?",
                 "p": ["Uporczywe zmęczenie nieustępujące po okresie może wskazywać na anemię (niedobór żelaza), niedoczynność tarczycy lub inne problemy. Jeśli męczysz się cały miesiąc, zbadaj krew."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Progesteron naturalnie obniża energię w fazie lutealnej",
                               "Zapotrzebowanie na sen przed okresem rośnie",
                               "Przewlekłe zmęczenie poza cyklem wymaga badań"]},
            "remember": ["Zmęczenie przed okresem = fizjologia",
                         "Lekki ruch i świeże powietrze dodają energii",
                         "Zmęczenie przez cały miesiąc → sprawdź żelazo i tarczycę"],
            "doctor": ["Zmęczenie utrzymujące się przez cały cykl",
                       "Senność mimo 8 godzin snu każdej nocy",
                       "Zmęczenie z bladością, zawrotami głowy i obfitymi okresami"],
            "summary": "Spadek energii przed okresem to działanie progesteronu. Pozwól sobie na więcej snu i lżejsze tempo, a jeśli zmęczenie trwa cały miesiąc — zbadaj żelazo i hormony tarczycy."
        },
    },
    {
        "slug": "ochota-na-slodycze",
        "title": "Dlaczego przed okresem mamy ochotę na słodycze?",
        "category": "Ciało i samopoczucie",
        "summary": "Hormonalne przyczyny zachcianek na czekoladę przed okresem i jak je oswoić bez poczucia winy.",
        "intro": "Ta górka czekolady przed okresem ma fizjologiczne podstawy. Dobra wiadomość: możesz ją jeść bez wyrzutów — i mądrze.",
        "read_minutes": 4,
        "illustration": "sweets",
        "tone": "peach",
        "badge": "",
        "phase": "pre_period",
        "keywords": "słodycze, czekolada, apetyt, PMS, serotonina, cukier, zachcianki",
        "related": ["pms", "wzdęcia", "cykl-a-apetyt"],
        "content": {
            "sections": [
                {"h": "Dlaczego akurat przed okresem?",
                 "p": ["W fazie lutealnej spada serotonina, a organizm domaga się szybkiej energii. Słodycze chwilowo podnoszą nastrój i poziom cukru — stąd odruchowa ochota na czekoladę czy cukierki."]},
                {"h": "Hormony i apetyt",
                 "ul": ["Spadek serotoniny → ochota na węglowodany",
                        "Progesteron → spowolnienie metabolizmu",
                        "Zmiany insuliny → spadki energii",
                        "Stres → dodatkowe „napady” słodkiego"]},
                {"h": "Jak to oswoić?",
                 "ul": ["Gorzka czekolada (70%+) — magnez i mniej cukru",
                        "Węglowodany złożone: płatki, pełne ziarna, banany",
                        "Białko w posiłkach stabilizuje cukier",
                        "Magnez i witamina B6 zmniejszają zachcianki",
                        "Nie zakazuj sobie — restrykcje wzmagają ochotę"]},
                {"h": "Bez poczucia winy",
                 "p": ["Ochota na słodkie przed okresem to sygnał hormonalny, nie „słaba wola”. Zjedzenie porcji czekolady nie jest porażką — jedz świadomie i ciesz się nią, zamiast walczyć."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Zachcianki na słodycze przed okresem mają podłoże serotoninowe",
                               "Białko i węglowodany złożone stabilizują poziom cukru",
                               "Zakazy potęgują ochotę — lepiej planować małe przyjemności"]},
            "remember": ["Czekolada przed okresem to biologia, nie brak silnej woli",
                         "Gorzka czekolada + orzechy = więcej magnezu",
                         "Zjedz i ciesz się — bez wyrzutów"],
            "doctor": ["Napadowe objadanie się wymykające się spod kontroli",
                       "Słodycze zastępujące regularne posiłki",
                       "Wahania nastroju bardzo silne z ochotą na jedzenie"],
            "summary": "Ochota na słodycze przed okresem to spadek serotoniny i zapotrzebowanie organizmu na energię. Sięgaj po gorzką czekoladę i stabilne posiłki, a restrykcje zamień na świadome przyjemności."
        },
    },
    {
        "slug": "tradzik-hormonalny",
        "title": "Trądzik hormonalny",
        "category": "Ciało i samopoczucie",
        "summary": "Dlaczego skóra psuje się przed okresem, jak dbać o cerę w rytmie cyklu i kiedy potrzebna jest dermatolog.",
        "intro": "Wypryski przed miesiączką to skutek wahań androgenów i progesteronu. Skóra ma swój „cykl” — warto się do niego dostosować.",
        "read_minutes": 5,
        "illustration": "skin",
        "tone": "mint",
        "badge": "",
        "phase": "any",
        "keywords": "trądzik, skóra, hormony, androgeny, miesiączka, cera, dermatolog",
        "related": ["pms", "cykl-a-skora", "stres-a-cykl"],
        "content": {
            "sections": [
                {"h": "Skąd się bierze trądzik hormonalny?",
                 "p": ["W fazie lutealnej wzrasta wrażliwość gruczołów łojowych na androgeny. Efekt: więcej sebum, zaskórniki i wypryski — najczęściej na brodzie, żuchwie i policzkach."]},
                {"h": "Kiedy się nasila?",
                 "p": ["Zmiany skórne zwykle pojawiają się na 1–2 tygodnie przed okresem i poprawiają się po miesiączce. Część kobiet widzi wyraźny „cykliczny” wzorzec, który łatwo wychwycić w dzienniku."]},
                {"h": "Pielęgnacja w rytmie cyklu",
                 "ul": ["Delikatne oczyszczanie 2 razy dziennie",
                        "Unikaj silnych peelingów i wyciskania zmian",
                        "Nawilżanie i łagodne składniki (niacynamid, kwas azelainowy)",
                        "W fazie lutealnej ogranicz cukier i nabiał (indywidualnie)",
                        "Ochrona SPF każdego dnia"]},
                {"h": "Kiedy dermatolog?",
                 "p": ["Jeśli trądzik jest bolesny, pozostawia blizny albo nie reaguje na pielęgnację, warto skonsultować się z dermatologiem. Często pomagają preparaty retinoidowe, antybiotyki miejscowe lub antykoncepcja o działaniu antyandrogennym (po konsultacji)."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Trądzik przed okresem wiąże się z wrażliwością na androgeny",
                               "Nie wyciskaj — to główna przyczyna blizn",
                               "Właściwe leczenie zwykle opanowuje zmiany w 2–3 miesiące"]},
            "remember": ["Wzorzec „skóra psuje się przed okresem” = hormonalny",
                         "Delikatna pielęgnacja wygrywa z agresywną",
                         "Bolesny lub bliznowaciejący trądzik → dermatolog"],
            "doctor": ["Trądzik torbielowaty, bolesny, z bliznami",
                       "Brak poprawy mimo pielęgnacji po 2–3 miesiącach",
                       "Trądzik z nieregularnymi cyklami lub nadmiernym owłosieniem"],
            "summary": "Trądzik hormonalny nasila się przed okresem przez androgeny i progesteron. Pomaga łagodna pielęgnacja, nawilżanie i cierpliwość, a przy ciężkich zmianach — konsultacja dermatologiczna."
        },
    },
    {
        "slug": "stres-a-cykl",
        "title": "Jak stres wpływa na cykl?",
        "category": "Ciało i samopoczucie",
        "summary": "Kortyzol, opóźniona owulacja i nieregularne miesiączki — związek między stresem a cyklem menstruacyjnym.",
        "intro": "Stres potrafi realnie przesunąć owulację i opóźnić okres. Zrozumienie tego mechanizmu pomaga przestać się martwić, że „coś jest z Tobą nie tak”.",
        "read_minutes": 5,
        "illustration": "mind",
        "tone": "rose",
        "badge": "Popularne",
        "phase": "any",
        "keywords": "stres, cykl, kortyzol, owulacja, miesiączka, nieregularność, relaks",
        "related": ["pms", "zmeczenie", "regularny-cykl"],
        "content": {
            "sections": [
                {"h": "Stres a hormony",
                 "p": ["Przewlekły stres podnosi kortyzol, a ten hamuje pracę osi podwzgórze–przysadka–jajniki. Efekt: owulacja może się opóźnić, a miesiączka przyjść później."]},
                {"h": "Opóźniona owulacja = późniejszy okres",
                 "p": ["Kiedy stres przesuwa owulację, wydłuża się cały cykl — miesiączka „spóźnia się”, choć nie ma z tym nic patologicznego. To najczęstszy mechanizm opóźnień u zdrowych kobiet."]},
                {"h": "Długotrwały stres",
                 "ul": ["Nieregularne cykle",
                        "Brak owulacji w pojedynczych miesiącach",
                        "Ból miesiączkowy nasilony",
                        "PMS silniejszy",
                        "W skrajnych przypadkach — zanik miesiączki"]},
                {"h": "Jak odzyskać regularność",
                 "p": ["Sen 7–8 h, regularny ruch, redukcja kofeiny, techniki oddechowe i realna przerwa od obowiązków. Obniżenie kortyzolu naturalnie przywraca cykl — organizm sam wraca do równowagi."]},
                {"h": "Kiedy zgłosić się do lekarza?",
                 "p": ["Jedno opóźnienie po stresie to norma. Jeśli miesiączki znikają na kilka miesięcy lub cykle są bardzo nieregularne mimo relaksu, warto sprawdzić hormony i tarczycę."]},
            ],
            "info": {"title": "Warto wiedzieć",
                     "items": ["Stres opóźnia owulację — a cykl przesuwa się całościowo",
                               "Jedno spóźnienie po stresującym okresie to norma, nie choroba",
                               "Kortyzol „wyłącza” prokreację — to mechanizm ochronny"]},
            "remember": ["Stres → opóźniona owulacja → późniejszy okres",
                         "Sen i ruch to najskuteczniejsze „leki” na kortyzol",
                         "Nie panikuj przy jednym opóźnieniu — obserwuj"],
            "doctor": ["Brak miesiączki przez ponad 3 miesiące",
                       "Duże nieregularności utrzymujące się kilka cykli",
                       "Opóźnienia z towarzyszącymi objawami tarczycowymi"],
            "summary": "Stres naturalnie spowalnia cykl — kortyzol przesuwa owulację, a okres przychodzi później. Wróć do snu, ruchu i oddechu, a regularność wróci sama. Przy długim zaniku miesiączki skonsultuj się z lekarzem."
        },
    },
]

# Kolejność wyświetlania kategorii na ekranie Inspiracje
CATEGORY_ORDER = [
    "Zdrowie reprodukcyjne",
    "Seks i intymność",
    "Podczas okresu",
    "Poznaj swój cykl",
    "Ciało i samopoczucie",
]
